### ISSUE TITLE
got an issue after moving to BRS v.3.3.3

### ISSUE THREAD

**Issue by K4r4Curt** [foxypool/foxy-miner#325]
Hi!
After moving to BRS v.3.3.3 and starting the foxy miner got an error:
Downloading scavenger: ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ | 0% | Speed: N/AThis error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
2022-02-18 00:39:53.603 [ERROR]  Error: read ECONNRESET

Have update the following after that:
node-v16.13.2-x64 --> node-v16.14.0-x64
foxy-miner-2.4.1-windows --> foxy-miner-2.6.0-windows

But the same error occured.
Before of that (in BRS v.3.3.0) all goes smooth and scavenger have been installed and worked already.
Tried to download and put scavenger-1.9.0-x86_64-pc-windows-msvc-cpu-only to user\.config\foxy-miner\miner\binaries\ but the foxy miner still try to download from source with the same error.
Tried to downgrade to v.3.3.0 also and got the same error.

Current node statement "online".
Don't know what to do for now. maybe someone

**Comment by felixbrucker** [comment]
It seems to fail to download the scav binary, can you make sure you can download it just fine from here? https://github.com/foxypool/foxy-miner/releases/download/0.0.0/scavenger-1.9.0-windows-x86_64-cpu-only.exe.zip

The file inside that zip is already named correctly for foxy-miner, so if the download via a browser works, but not in foxy-miner for some reason, then you can just put the exe fro mthe zip in the binary directory and it should work

**Comment by K4r4Curt** [comment]
moved *.zip and *.exe file downloaded from source to /binaries folder, make a settings to foxy-miner.yaml and looks like it let me pass to the next error:
2022-02-18 02:37:35.791 [INFO]  Config loaded from C:\Users\.config\foxy-miner\foxy-miner.yaml successfully
2022-02-18 02:37:38.827 [ERROR]  FoxyPool BHD | Connection outage detected ..
2022-02-18 02:37:38.828 [ERROR]  FoxyPool SIGNA | Connection outage detected ..

Then I've reinstall Node.js and the problem have not gone.
So for now I've stucked at [ERROR]  FoxyPool | Connection outage detected

**Comment by felixbrucker** [comment]
It looks like something is blocking foxy-miner from internet access, double check your firewall or similar is not blocking it

**Comment by K4r4Curt** [comment]
the settings I've changed in foxy-miner.yaml:

upstreams:
  - name: FoxyPool BHD
    type: foxypool
    color: '#e25898'
    coin: BHD
    distributionRatio: 0-100
    payoutAddress: "MY-BHD-PAYOUT ADDRESS"
    accountName: "some"
    minerName: "some"
    weight: 20
    doNotInterruptAbovePercent: 50
  - name: FoxyPool SIGNA
    type: foxypool
    color: '#4959ff'
    coin: 'SIGNA'
    distributionRatio: 0-100
    payoutAddress: "MY-SIGNA-PAYOUT ADDRESS"
    accountName: "some"
    minerName: "some"
    weight: 10
    doNotInterruptAbovePercent: 50

**Comment by K4r4Curt** [comment]
I've checked the firewall rules and add a rule for port at start of an issue:
non-local port: any (nothing)
local port: 8123
direction: IN-/OUT going
protocol: TCP
non-local address: any (nothing)
local address: any (nothing)

**Comment by K4r4Curt** [comment]
some Node.js v.16.14.0 modules requires Python and  VisualStudio Tools for compilation and it should install with Node.js package.
But when I'm installing the Node.js as is it rolls up some error when I've tried install Python and  VisualStudio Tools from Node.js package.
![1645174538739](https://user-images.githubusercontent.com/52543018/154651063-d04dd783-a6f4-4e13-b7c3-c776d44e32f2.jpg)

I've uninstall the Node.js, then install Python 3.10 and then VisualStudio Tools 2022 with the following packets:
![1645174538757](https://user-images.githubusercontent.com/52543018/154651428-2a8ecb73-5f2a-46a9-96e1-832995689dd2.jpg)
 
Then install Node.js.
I've started  foxy-miner after all this proccess and got the same error with "connection outage".

I'm thinking that there is some errors with Node.js dependencies, but don't have any thoughts where to go.

Maybe someone got the same problems and have a solution?

**Comment by K4r4Curt** [comment]
It's certainly because of some net settings rule, but there is no obvious reason for it.
I've made a trustworthy settings in firewall/antivirus for all applets that got dependencies with SIGNA node and foxy-miner too;
I've shut down antivirus before start of foxy-miner;
Downloaded and rolled-up the github release of foxy-miner (again);
Backed up foxy-miner.yaml and made the miner settings from scratch.

After all of that it still with "connection outage" after foxy-miner starts.
Maybe there is some other specific port that needs to be open including port 8123?

**Comment by felixbrucker** [comment]
again, port 8123 is the p2p port for the signum node, foxy miner does not connect to your signum node, nor does it open any port for external use. It connects to the pool gateway over http.
