### ISSUE TITLE
Disk Scan Causes Crash

### ISSUE THREAD

**Issue by sdooweloc** [foxypool/foxy-miner#412]
Trying to use foxy on Arch installed with npm to mine however any time it tries to run through the disk scan it ends up crashing as below. 
Is there a way to restrict the scan to only disks I know have plots or is there a base config I could manually populate to avoid needing to go through the scan? 

```
⠦ Searching for plot files in /media/Games/GOG Games/Disco Elysium  The Final Cut/prefix/dosdevices/z:/proc/1734712/cwd/bin. Found plots: 46 | Scanned directories: 28488
<--- Last few GCs --->

[2227016:0x557a7e9c6760]    99178 ms: Mark-sweep 4044.3 (4131.9) -> 4038.0 (4141.4) MB, 2064.8 / 33.3 ms  (average mu = 0.816, current mu = 0.161) allocation failure scavenge might not succeed
[2227016:0x557a7e9c6760]   102940 ms: Mark-sweep 4053.7 (4141.4) -> 4046.9 (4150.1) MB, 3709.5 / 27.6 ms  (average mu = 0.562, current mu = 0.014) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x557a7c786745 node::Abort() [node]
 2: 0x557a7c62c450 node::OnFatalError(char const*, char const*) [node]
 3: 0x557a7c97d0da v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0x557a7c97d498 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0x557a7cb1e4ca  [node]
 6: 0x557a7cb3590f v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 7: 0x557a7cb37d4b v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0x557a7cb37ddc v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0x557a7cafd384 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x557a7ce3a457 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x557a7d1f9379  [node]
[1]    2227016 IOT instruction (core dumped)  foxy-miner
```

**Comment by felixbrucker** [comment]
You can not change the directories to scan during the first run wizard, however you can create a config manually, then it wont go through the first run wizard (and thus the scan). The reason it scans so deep is that `Disco Elysium  The Final Cut` contains `disc` which is a whitelisted directory keyword: https://github.com/foxypool/foxy-miner/blob/e6cb2a0451e9805b38e0d542cea2f761c8996b51/lib/plot-file-finder/plot-file-finder.js#L22-L31

You can check out https://docs.foxypool.io/proof-of-capacity/foxy-miner/configuration/#configuration-example for a full config example

**Comment by sdooweloc** [comment]
Ahh okay thanks. I hadnt gotten down to digging through the actual finder code yet so that explains it. Now getting issues with other things but I think I know what is going on there so that is a non-issue as far as this thread is concerned. Thank you!
